package_dirs:
- pkgs
- base

hook_import_dirs:
- base

parameters:
  BASH: /bin/bash
  PROLOGUE: | # by default, PROLOGUE is a no-op

  # Note, if you change pyver,
  # you should probably change the following two lines as well.
  pyver: '3.7'  # as in used in lib/pythonX.Y/site-packages
  python_site_packages_rel: 'lib/python3.7/site-packages'
  python_host_packages: '/usr/lib/python3.7/dist-packages'

  use_python_host_packages: false
